name: Update all wl-docs

on:
  workflow_dispatch:

jobs:
  update_wanderlust:
    uses: ./.github/workflows/update_docs.yml
    with:
      repository_name: ${{ vars.WL_REPOSITORY_NAME }}
      source_files: ${{ vars.WL_SOURCE_FILES }}
      texi_files: ${{ vars.WL_TEXI_FILES}}
  update_flim:
    uses: ./.github/workflows/update_docs.yml
    with:
      repository_name: ${{ vars.FLIM_REPOSITORY_NAME }}
      source_files: ${{ vars.FLIM_SOURCE_FILES }}
      texi_files: ${{ vars.FLIM_TEXI_FILES}}
  update_semi:
    uses: ./.github/workflows/update_docs.yml
    with:
      repository_name: ${{ vars.SEMI_REPOSITORY_NAME }}
      source_files: ${{ vars.SEMI_SOURCE_FILES }}
      texi_files: ${{ vars.SEMI_TEXI_FILES}}
